#!/bin/bash

# This is a thin wrapper around dobbscoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using dobbscoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_BITCOIND

# Grab the value of $REAL_BITCOINCLI which may be dobbscoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_BITCOINCLI}" "$@" | sed 's/\r//'
